#!flask/bin/python
from app import db,models
import sys, getopt

def main(argv):
	id = ''
	mail = ''
	partner = ''
	empresa = ''
	contacto = ''
	telefono = ''
	movil = ''
	try:
		opts, args = getopt.getopt(argv,"hi:p:e:c:t:m:em:",["id=","partner=","empresa=","contacto=","telefono=","movil=","mail="])
	except getopt.GetoptError:
		print 'peta al inicio'
		sys.exit(2)
	for opt, arg in opts:
		if opt == '-h':
			print 'test.py -i <inputfile> -o <outputfile>'
			sys.exit()
		elif opt in ("-i", "--id"):
			id = arg
		elif opt in ("-p", "--partner"):
			partner = arg
		elif opt in ("-e","--empresa"):
			empresa = arg
		elif opt in ("-c","--contacto"):
			contacto = arg
		elif opt in ("-t","--telefono"):
			telefono = arg
		elif opt in ("-m","--movil"):
			movil = arg
		elif opt in ("-em","--mail"):
			mail = arg
	u = models.Profile(id=id, partner=partner,empresa=empresa,contacto=contacto,telefono=telefono,movil=movil,mail=mail)
	db.session.add(u)
	db.session.commit()	

if __name__ == "__main__":
   main(sys.argv[1:])
